---

# see https://github.com/fuxingloh/multi-labeler
version: v1
labels:

  # thses labels are used to draft relases.
  - label: "enhancement"
    matcher:
      branch: "^(feat|feature)-.*"
  - label: "bugfix"
    matcher:
      branch: "^(bugfix|fix)-.*"
  - label: "doc"
    matcher:
      branch: "^(doc|documentation)-.*"
  - label: "ci"
    matcher:
      branch: "^ci-.*"
  - label: "chore"
    matcher:
      branch: "^chore-.*"

  # area indicates which files are modified in the PR.
  - label: "area:doc"
    sync: true
    matcher:
      files:
        any:
          - "include/**"
          - "doc/**"
  - label: "area:src"
    sync: true
    matcher:
      files:
        any:
          - "include/**"
          - "src/**"
          - "examples/**"
          - "component.mk"
