---
name-template: "$NEXT_PATCH_VERSION"
tag-template: "$NEXT_PATCH_VERSION"
categories:
  - title: Features
    label: feature
  - title: Bug Fixes
    labels:
      - bugfix
      - fix
  - title: Documentation
    label: documentation
  - title: CI
    label: ci
change-template: "* $TITLE (#$NUMBER)"
template: |
  ## Release $NEXT_PATCH_VERSION

  $CHANGES
