---

name: clang-format
on:
  - pull_request
jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run clang-format
        uses: DoozyX/clang-format-lint-action@v0.13
        with:
          exclude: "./components"
          extensions: 'h,c'
          clangFormatVersion: 13
