---

# leave a comment about CI issues when a PR is labled

name: Comment on CI issues
on:
  pull_request:
    types:
      - labeled
jobs:
  on-labeled:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context for debugging
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))
