---
# add or remove labels by workflow status.

name: Label by workflow status
on:
  workflow_run:
    workflows:
      - test-clang-format
    types:
      - completed

jobs:
  on-completed:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context for debugging
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))

  on-clang-format-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'test-clang-format' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Add success label
        uses: actions/github-script@v6
        with:
          script: |
            try {
              github.rest.issues.addLabels({
                issue_number: context.payload.workflow_run.pull_requests[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["ci/clang-format:success"]
              });
            } catch(e) {
              console.log(e);
            }

  on-clang-format-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'test-clang-format' && github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Add failure label
        uses: actions/github-script@v6
        with:
          script: |
            try {
              github.rest.issues.addLabels({
                issue_number: context.payload.workflow_run.pull_requests[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ["ci/clang-format:failure"]
              });
            } catch(e) {
              console.log(e);
            }
