---

# add or remove labels by workflow status.

name: Label by workflow status
on:
  workflow_run:
    workflows:
      - test-clang-format
    types:
      - completed

jobs:
  on-clang-format-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'test-clang-format' && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Add success label
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.workflow_run.pull_requests.number)

  on-clang-format-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.name == 'test-clang-format' && github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Add failure label
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.workflow_run.pull_requests.number)
