---
# add or remove labels by workflow status.

name: Label by workflow status
on:
  workflow_run:
    # workflows that should run this workflow must be listed by name here
    workflows:
      - Build doc
      - Build examples
      - clang-format
      - yamllint

    types:
      - completed

jobs:
  on-completed:
    runs-on: ubuntu-latest
    steps:
      - name: Dump context for debugging
        uses: actions/github-script@v6
        with:
          script: |
            console.log(JSON.stringify(context, null, 2))

  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Add success label
        uses: actions/github-script@v6
        with:
          script: |
            label_success_name = "ci" + "/" + context.payload.workflow_run.name + "/" + "success"
            label_failure_name = "ci" + "/" + context.payload.workflow_run.name + "/" + "failure"
            try {
              await github.rest.issues.addLabels({
                issue_number: context.payload.workflow_run.pull_requests[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [label_success_name]
              });
            } catch(e) {
              core.error(e);
              core.setFailed(e.message);
            }
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.payload.workflow_run.pull_requests[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label_failure_name
              });
            } catch(e) {
              if (!e.message.includes('Label does not exist')) {
                core.error(e);
                core.setFailed(e.message);
              }
            }
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Add failure label
        uses: actions/github-script@v6
        with:
          script: |
            label_success_name = "ci" + "/" + context.payload.workflow_run.name + "/" + "success"
            label_failure_name = "ci" + "/" + context.payload.workflow_run.name + "/" + "failure"
            try {
              await github.rest.issues.addLabels({
                issue_number: context.payload.workflow_run.pull_requests[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: [label_failure_name]
              });
            } catch(e) {
              core.error(e);
              core.setFailed(e.message);
            }
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.payload.workflow_run.pull_requests[0].number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: label_success_name
              });
            } catch(e) {
              if (!e.message.includes('Label does not exist')) {
                core.error(e);
                core.setFailed(e.message);
              }
            }
