name: Release
on:
  push:
    branches:
      - release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          default-branch: release
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"doc","section":"Documentation","hidden":false},{"type":"bugfix","section":"Bug Fixes","hidden":false}]'
